### PR TITLE
Resolve relative paths when adding sources

### LINKED ISSUE #41: Relative paths using .. fail with --source
Use case: Test script(s) under ``tests/`` and source code under ``scr/``, running from the tests folder try using ``--source ../src/`` and it fails.

Work around: Use the absolute path

I believe the ``..`` need expanding here:

```python
    def addSource(self, source : Path):
        if isinstance(source, str):
            source = Path(source)
        if not source.is_absolute():
            source = self.cwd / source
        self.sources.append(source)
```

i.e. https://github.com/plasma-umass/slipcover/blob/v0.3.1/src/slipcover/importer.py#L61

It should probably call https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve but there could be side effects that I've not considered. However, this seems to work for me:

```python
    def addSource(self, source : Path):
        if isinstance(source, str):
            source = Path(source)
        if not source.is_absolute():
            source = (self.cwd / source).resolve()
        self.sources.append(source)
```

### PR DESCRIPTION
**Pull request by peterjc**
Enables use of .. in --source arguments.

Closes #41

### CODE REVIEW

**Comment by jaltmayerpizzorno** [comment]
Thank you!  Would you mind creating a test for it?

**Comment by jaltmayerpizzorno** [comment]
Mm, good question. Probably `tmp` would be best. `tests` is getting a bit crowded.
Thank you!

**Comment by peterjc** [comment]
It might be quicker for you to take over the PR and write a test, this was a quick drive-by exploration of the tool late last night, and I have too many more pressing tasks this week to give this one justice. Sorry.

**Comment by jaltmayerpizzorno** [comment]
No problem, thank you for contributing the change (and bug report!). I'll leave open until I can work on it.

**Pull request merged**
